# Generated by Django 2.0.6 on 2018-08-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'permissions': {('can_view_assessment', 'can view assessment')}},
        ),
    ]
