# Generated by Django 2.0.6 on 2018-08-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20180801_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentresult',
            options={'permissions': {('can_view_result_faculty', 'can view result faculty'), ('can_view_result_student', 'can view result student')}},
        ),
    ]
