# Generated by Django 2.0.6 on 2018-08-01 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_join', models.DateField()),
                ('date_of_leave', models.DateField()),
                ('qualification', models.CharField(max_length=50)),
                ('designation', models.CharField(choices=[('AST_PROF', 'Assistant Professor'), ('ASC_PROF', 'Associate Professor'), ('PROF', 'Professor'), ('OT', 'Other')], max_length=10)),
                ('specialization', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('submit', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=None, to='department.Department')),
                ('user', models.OneToOneField(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
