# Generated by Django 2.0.6 on 2018-08-01 07:48

from django.conf import settings
from django.db import migrations, models
import enumerations.enum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=None, related_name='block_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=None, related_name='block_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(max_length=20, unique=True)),
                ('group_list', models.TextField()),
                ('group_id', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('M', 'Message'), ('N', 'Notice'), ('B', 'Broadcast')], default=enumerations.enum.MessageType('Message'), max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=250)),
                ('attachment', models.FileField(blank=True, upload_to='message_attachments')),
                ('receiver', models.ForeignKey(null=True, on_delete=None, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('receiver_group', models.ForeignKey(null=True, on_delete=None, to='communication.Group')),
                ('sender', models.ForeignKey(on_delete=None, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('information', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='')),
                ('duration', models.IntegerField(default=31, help_text='Default 31 days,Enter to Overwrite.(No of Days)')),
            ],
        ),
    ]
