# Generated by Django 2.0.6 on 2018-08-01 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterPublished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField()),
                ('attachment', models.FileField(upload_to='')),
                ('text', models.TextField()),
                ('editor', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('attachment', models.FileField(upload_to='')),
                ('date', models.DateTimeField()),
                ('edition', models.PositiveSmallIntegerField()),
                ('author', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('editorial_name', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('volume', models.PositiveSmallIntegerField()),
                ('edition', models.PositiveSmallIntegerField()),
                ('pages', models.IntegerField()),
                ('date_of_addition', models.DateTimeField()),
                ('abstract', models.TextField()),
                ('publisher_name', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=None, to='publications.Publication')),
            ],
        ),
    ]
