# Generated by Django 2.0.6 on 2018-08-01 07:48

from django.conf import settings
from django.db import migrations, models
import enumerations.enum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('program', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('SEM_1', '1st Semester'), ('SEM_2', '2nd Semester'), ('SEM_3', '3rd Semester'), ('SEM_4', '4th Semester'), ('SEM_5', '5th Semester'), ('SEM_6', '6th Semester'), ('SEM_7', '7th Semester'), ('SEM_8', '8th Semester')], default=enumerations.enum.Semester('1st Semester'), max_length=10)),
                ('date_of_admission', models.DateField(null=True)),
                ('mother_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('area_of_interest', models.TextField(blank=True)),
                ('carrier_objective', models.TextField(blank=True)),
                ('submit', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=None, to='department.Department')),
                ('program', models.ForeignKey(on_delete=None, to='program.Program')),
                ('user', models.OneToOneField(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
