# Generated by Django 2.0.6 on 2018-08-01 07:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('OT', 'Other')], default='', max_length=3)),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=10)),
                ('state', models.CharField(default='', max_length=10)),
                ('contact', models.CharField(default='+919876543210', max_length=15)),
                ('photo', models.ImageField(blank=True, help_text='Your Photo name should be same as your name', upload_to='profile_photo')),
                ('category', models.CharField(choices=[('GEN', 'General'), ('OBC', 'Other Backward Class'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe')], default='', max_length=5)),
                ('blood_group', models.CharField(choices=[('OM', 'O-Minus'), ('OP', 'O-Positive'), ('AM', 'A-Minus'), ('AP', 'A-Positive'), ('BM', 'B-Minus'), ('ABM', 'AB-Minus'), ('ABP', 'AB-Positive'), ('BP', 'B-Positive')], default='', max_length=5)),
                ('type', models.CharField(choices=[('S', 'Student'), ('F', 'Faculty'), ('U', 'User'), ('A', 'Alumni')], default='', max_length=3)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_profile', 'view user profile'),),
            },
        ),
    ]
