# Generated by Django 2.0.6 on 2018-08-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('head_name', models.CharField(max_length=50)),
                ('foundation_year', models.CharField(max_length=4)),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('resources', models.TextField()),
                ('rules_reg', models.TextField()),
                ('calendar', models.IntegerField()),
            ],
        ),
    ]
